#https://github.com/haproxy-ingress/charts/blob/master/haproxy-ingress/README.md#configuration
controller:
  hostNetwork: true
  #  dnsPolicy: ClusterFirstWithHostNet
  #  Kind: Deployment
  replicaCount: 1
  service:
    externalTrafficPolicy: Local
    type: NodePort
    httpPorts:
    - port: 80
      targetPort: http
      nodePort: 30001 #暴露给internet访问的端口
defaultBackend:
  #  enabled: false
  image:
    repository: registry.aliyuncs.com/google_containers/defaultbackend #使用国内镜像，k8s.gcr.io => registry.aliyuncs.com/google_containers
