apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: go-web-service-ingress
spec:
  backend: #连接后端服务，相当于nginx的upstream
    serviceName: go-web-service
    servicePort: 8080
