---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  type: NodePort
  #type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 3001
    nodePort: 30000
  selector:
    name: go-web-app

