apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_USER: guobin
  MYSQL_PASSWORD: "222222"
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: "111111" #root用户本来就存在，只需要设置root秘密就可以了
